defaults:
  - inference_base
  - generation: uncond_codes_800
  - _self_

ckpt_path: ./store/test_release_diffusion/checkpoints  
ckpt_name: last.ckpt
autoencoder_ckpt_path: ./checkpoints_laproteina/AE2_ucond_800.ckpt

generation:
  model:
    bb_ca:
      simulation_step_params:
        sc_scale_noise: 0.15  # scale used to multiply noise if mode == sc
    local_latents:
      simulation_step_params:
        sc_scale_noise: 0.05  # scale used to multiply noise if mode == sc
